blog/urls.py
from blog import views
from django.conf.urls import url
from django.urls import path, re_path


app_name = 'blog'
urlpatterns = [
    
    re_path(r'^blog/(?P<id>\d+)/(?P<slug>[\w-]+)/', views.post_detail, name="post_detail"),
    url(r'^(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    url(r'^(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    re_path('post_create/', views.post_create, name="post_create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from blog import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blog'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    # path('', views.post_list, name="post_list"),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('likes/', views.like_post, name="like_post"),
    # Password Reset Url's
    # path('password-reset/', auth_views.password_reset, name="password_reset_form"),
    # path('password-reset/done/', auth_views.password_reset_done, name="password_reset_done"),
    # re_path('password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/', auth_views.password_reset_confirm, name="password_reset_confirm"), 
    # path('password-reset/complete/', auth_views.password_reset_complete, name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")

class Post(models.Model):
    objects = models.Manager()      # default manager
    
    published = PublishedManager()   # Custom model manager

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )



    title       =   models.CharField(max_length=250)
    slug        =   models.SlugField(max_length=250)
    author      =   models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body        =   models.TextField()
    likes       =   models.ManyToManyField(User, related_name='likes', blank=True)
    created     =   models.DateTimeField(auto_now_add=True)
    updated     =   models.DateTimeField(auto_now=True)
    status      =   models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')


    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id, self.slug])

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True) 
    photo = models.ImageField(null=True, blank=True)


    def __str__(self):
        return "profile of User {}".format(self.user.username)



class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


    def __str__(self):
        return self.post.title + "Image"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('self', null=True, related_name="replies", on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now=True)


    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

blog/forms.py
from django import forms
from .models import Post, Profile, Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'form-control'}))
    # body = forms.Field(label="Text", widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model =Post
        fields = (
            'title',
            'body',
            'status',
        )


class UserLoginForm(forms.Form):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder': 'Enter Password Here...', 'class': 'form-control'}))
    confirm_password = forms.CharField(widget = forms.PasswordInput(attrs = {'placeholder': 'Confirm Password...', 'class': 'form-control'}))
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="last Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label="EmailAddress", widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password


class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly','class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

class ProfileEditForm(forms.ModelForm):
    dob = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
   

    class Meta:
        model = Profile
        exclude = ('user',)
        fields = (
                'dob',  
                'photo',              
            )


class PostEditForm(forms.ModelForm):
    class Meta:
        model =Post
        fields = (
            'title',
            'body',
            'status',
        )


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'col':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts                       import render, get_object_or_404, redirect
from django.urls                            import reverse
from django.contrib.auth.decorators         import login_required
from django.contrib.auth.models             import User
from django.http                            import HttpResponse, HttpResponseRedirect, JsonResponse, Http404 #new
from datetime                               import datetime
from .forms                                 import *
from .models                                import Post, Profile, Images
from django.contrib.auth                    import authenticate, login, logout
from django.db.models                       import Q
from django.core.paginator                  import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader                 import render_to_string
from django.forms                           import modelformset_factory
from django.contrib                         import messages
# Create your views here.

# def index(request):
#     return HttpResponse("hello django")

def post_list(request):
    post_list = Post.published.all().order_by('-id')
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(
            Q(title__icontains=query)|
            Q(author__username=query)|
            Q(body__icontains=query)
            )
    
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]
    
    context = {
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)


def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)

def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False;
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()

    context ={
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})
        
    return render(request, 'blog/post_detail.html', context)

def like_post(request):
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False;
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context ={
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes()
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})
        

def post_create(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            for f in formset:
                try:
                    photo = Images(post=post, image=f.cleaned_data['image'])
                    photo.save()
                except:
                    break
            messages.success(request, "Post has been successfully created.")
            return redirect('post_list')



    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)

    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)

        if form.is_valid() and formset.is_valid():
            print(formset.cleaned_data)
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)

            for index, f in  enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                         photo = Images(post=post, image=f.cleaned_data.get('image'))
                         d = Images.objects.get(id=data[index].id)
                         d.image = photo.image
                         d.save()
            messages.success(request, "{} has been successfully updated!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))

    context = {
        'form': form,
        'post': post,
        'formset': formset,
    }
    return render(request, 'blog/post_edit.html', context)


def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.author:
        raise Http404
    post.delete()
    messages.warning(request, "post has been successfully deleted!!")
    return redirect('post_list')




def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not activate")
            else:
                return HttpResponse("User in None")
    else:
        form = UserLoginForm()

    context = {
            'form': form,
        }
    return render(request, 'blog/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('home')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return redirect('post_list')

    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }

    return render(request, 'registration/register.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse("blog:edit_profile"))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user)
        

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'blog/edit_profile.html', context)

templates/blog/alert.html
<div class="messages">
    {% if messages %}
    
        {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">
                {{ message }}
            </p>
            
        {% endfor %}
            
    
    {% endif %}
</div>

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style1.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <title>
        
        {% block title %}
            Green's Blog
        {% endblock title %}
            
    </title>
</head>
<body>
    {% include 'blog/navbar.html' %}
    <div class="container-fluid">
            {% block content %}
            {% endblock content %}
    </div>
   
       

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(event){

        $('#delete').click(function(event){
            return confirm("Are you sure to delete te post?")
        });

        $('.reply-btn').click(function(){
            $(this).parent().parent().next('.replied-comments').fadeToggle()
        });

        $(function(){
            setTimeout(function(){
                $('.alert').slideUp(2000);
            }, 3000);
        });


        $(document).on('click', '#like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
               type: 'POST',
               url: '{% url "like_post" %}',
               data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: 'json',
               success: function(response){
                   $('#like-section').html(response['form'])
                   console.log($('#like-section').html(response['form']));
               },
               error: function(rs, e){
                   console.log(rs.responseText);
               },
            });
        });


        $(document).on('submit', '.comment-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function(response){
                    $('.main-comment-section').html(response['form']);
                    $('textarea').val('');
                    $('.reply-btn').click(function(){
                        $(this).parent().parent().next('.replied-comments').fadeToggle();
                        $('textarea').val('');
                    });
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });

        $(document).on('submit', '.reply-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function(response){
                    $('.main-comment-section').html(response['form']);
                    $('textarea').val('');
                    $('.reply-btn').click(function(){
                        $(this).parent().parent().next('.replied-comments').fadeToggle();
                        $('textarea').val('');
                    });
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });

    });



</script>
</html>

templates/blog/comments.html
<div class="container-fluid mt-2">
        <div class="form-group row">
            <form method="POST" class="comment-form" action=".">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    
                    {% if request.user.is_authenticated %}       
                        <input type="submit" value="Submit" class="btn btn-outline-success" >
                    {% else %}
                        <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                    {% endif %}
                    
                </form>
        </div>
</div>
    {{ comments.count }} Comment{{ comments|pluralize }}
    {% for comment in comments %}
    <blockquote class="blockquote">
        <p class="mb-0"> <small>{{ comment.content }}</small> </p>
        <footer class="blockquote-footer"> <small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
            <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
            
        </footer>
      </blockquote>
      
      <div class="replied-comments container mt-2" style="display:none;" >
          
          {% for reply in comment.replies.all %}
          <blockquote class="blockquote">
                <p class="mb-0"> <small>{{ reply.content }}</small> </p>
                <footer class="blockquote-footer"> <small> by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
                
                
                </footer>
              </blockquote>
          {% endfor %}
              
          <div class="form-group row">
            <form method="POST" class="reply-form" action=".">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}" id="">
                {{ comment_form.as_p }}
                
                {% if request.user.is_authenticated %}       
                    <input type="submit" value="Submit" class="btn btn-outline-success" >
                {% else %}
                    <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                {% endif %}
               
            </form>
          </div>
      </div>

    {% endfor %}

 

templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block title %}Edit Profile | {{ block.super }}{% endblock %}
{% block content %}
  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Save Changes" class="btn btn-outline-success">
  </form>
{% endblock %}

templates/blog/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}
<form action="{% url 'like_post' %}" method="POST">
        {% csrf_token %}
        {% if is_liked %}
            <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
        {% else %}    
        <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
        {% endif %}
    </form>

templates/blog/login.html
{% extends 'blog/base.html' %}


{% block content %}
<!-- <div class="container">
    <div class="col-sm-6"> 
        <div class="panel panel-default">
            <div class="panel-heading"> Login </div>           
            <div class="panel-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <small>
                        <a href="{% url 'register' %}"> Register </a> |
                        <a href="{% url 'password_reset' %}">Forgetten your password?</a>
                    </small>
                    <br>
                    <input type="submit" value="login" class="btn btn-outline-success col-12">
                    <br>
                    <p> -- OR --</p>
                    <a href="{% url 'social:begin' 'google-oauth2' %}">
                            <button type="button" name="button" class="btn btn-danger col-12">Google</button>
                    </a>
                </form>
            </div>
        </div>
    </div> 
</div> -->
<div class="container">
        <div class="row">
          <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
              <div class="card-body">
                <h5 class="card-title text-center">Sign In</h5>
                <form class="form-signin" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <small>
                            <a href="{% url 'register' %}"> Register </a> |
                            <a href="{% url 'password_reset' %}">Forgetten your password?</a>
                        </small>
                        <br>
                        <input type="submit" value="login" class="btn btn-outline-success col-12">
                        <br>
                        <p> -- OR --</p>
                        <a href="{% url 'social:begin' 'google-oauth2' %}">
                                <button type="button" name="button" class="btn btn-danger col-12">Google</button>
                        </a>
                    </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

    

templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'post_list' %}"id=>Green's Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item"><a  class="nav-link" href="{% url 'post_list' %}">Blog</a></li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'post_list' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Posts" aria-label="Search" name='q'>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if request.user.profile.photo %}
                <img src="{{ request.user.profile.photo.url }}" alt="icon image" class="navbar-img">
                {% else %}
                <img src="/media/download.jpeg" alt="" class="navbar-img">
                {% endif %}
                <span>Hi {{ request.user|capfirst }}</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'blog:edit_profile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'blog:post_create' %}">Create Post</a>

                <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
                
              </div>
            </li>
            {% else %}
          <li class="nav-item">
            <a href="{% url 'user_login' %}" class="nav-link">Login</a>
          </li>
          {% endif %}
      </ul>
     
    </div>
  </nav>

  

templates/blog/post_detail.html
 
{% extends 'blog/base.html' %}


{% block title %} {{ post.title }} | {{ block.super }} {% endblock title %}
    

{% block content %}
{% include 'blog/alert.html' %}


<div class="container-fluid">
    <h3>{{ post.title }}</h3>
    <small>Post created by: {{ post.author }}</small>
    <hr>
    <p>{{ post.body }}</p>  
    <hr>
    <div class="row galary">
        {% for p in post.images_set.all %}
            <div class="col-md-3">
                <img src="{{ p.image.url }}" alt="Images Not Found" class="img-thumbnail">
            </div>
        {% endfor %}
    </div>

    <div id="like-section">
        {% include 'blog/like_section.html' %}
    </div>
    {% if post.author == request.user %}
    <div class="section-1" style="float:right;">
        <a href="{% url 'blog:post_edit' id=post.id %}">
            <button type="button" class="btn btn-outline-success">Edit</button>
        </a>
        <a href="{% url 'blog:post_delete' id=post.id %}" id="delete">
            <button type="button" class="btn btn-danger">Delete</button>
        </a>
    </div>
    {% endif %}

    <br><br>
    <hr>
    <div class="main-comment-section">
        {% include 'blog/comments.html' %}
            
    </div>
</div>
{% endblock content %}
    
    
   

templates/blog/post_edit.html
{% extends 'blog/base.html' %}


{% block title %}
    {{ post.title }} | Edit
{% endblock title %}
    

{% block content %}
   <form enctype="multipart/form-data" method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for f in formset %}
            {{ f.as_p }}
        {% endfor %}
            
        <input type="submit" value="Update" class="btn btn-success">
   </form>
{% endblock content %}
    